# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Learning Objective

At the end of this experiment, you will be able to:

* perform Data preprocessing

In [ ]:
#@title  Mini Hackathon Walkthrough
from IPython.display import HTML

HTML("""<video width="640" height="420" controls>
  <source src="https://cdn.talentsprint.com/talentsprint/archives/sc/aiml/aiml_batch_15/preview_videos/Mini_Hackathon_Data_Munging_Briefing.mp4" type="video/mp4">
</video>
""")

## Problem Statement

We will be using district wise demographics, enrollments, and teacher indicator data to predict whether the literacy rate is high/ medium/ low in each district.

### Data Preprocessing

Data preprocessing is an important step in solving every machine learning problem. Most of
the datasets used with Machine Learning problems need to be processed / cleaned / transformed
so that a Machine Learning algorithm can be trained on it.

There are different steps involved in Data Preprocessing. These steps are as follows:

    1. Data Cleaning → In this step the primary focus is on
        - Handling missing data
        - Handling noisy data
        - Detection and removal of outliers
    
    2. Data Integration → This process is used when data is gathered from various data sources and data are combined to form consistent data.
    This data after performing cleaning is used for analysis.
    
    3. Data Transformation → In this step we will convert the raw data into a specified format according to the need of the model we are building.
    There are many options used for transforming the data as below:
        - Normalization
        - Aggregation
        - Generalization
        
    4. Data Reduction → Following data transformation and scaling, the redundancy within the data is removed and is organized efficiently.

### Total Marks  = 20

In [1]:
# @title Download the datasets
from IPython import get_ipython

ipython = get_ipython()

notebook="U1_MH1_Data_Munging" #name of the notebook

def setup():
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/B15_Data_Munging.zip")
    ipython.magic("sx unzip B15_Data_Munging.zip")
    print("Data downloaded successfully")
    return

setup()

Data downloaded successfully

In [2]:
!ls

B15_Data_Munging.zip
Districtwise_Basicdata.csv
Districtwise_Enrollment_details_indicator.csv
Districtwise_Teacher_indicator.csv
sample_data

## Exercise 1 - Load and Explore the Data (3 Marks)
1. We have three different files

  * Districtwise_Basicdata.csv
  * Districtwise_Enrollment_details_indicator.csv
  * Districtwise_Teacher_indicator.csv

  These files contain the necessary data to solve the problem. <br>

2. Load the files based on **team allocation** mentioned below. Observe the header level details, data records while loading the data.
  
  Hint : Use read_csv from pandas with [skiprows or header](https://towardsdatascience.com/import-csv-files-as-pandas-dataframe-with-skiprows-skipfooter-usecols-index-col-and-header-fbf67a2f92a) options.

3. Read the columns of the dataset and rename them if required.

  Hint : Rename column names (if any) using the following [link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

Team allocation for dataset selection

    Team A = 1,3,5,7,9,11,13,15
        Districtwise_Basicdata.csv
        Districtwise_Enrollment_details_indicator.csv

    Team B = 2,4,6,8,10,12,14
        Districtwise_Basicdata.csv
        Districtwise_Teacher_indicator.csv

In [4]:
# Importing all the required packages and add necessary imports if required
import pandas as pd
import numpy as np

In [66]:
# YOUR CODE HERE for loading and exploring the datasets
#df1=pd.read_csv('/content/Districtwise_Basicdata.csv')
df2=pd.read_csv('/content/Districtwise_Enrollment_details_indicator.csv')
#df3=pd.read_csv('/content/Districtwise_Teacher_indicator.csv')

In [25]:
df2.iloc[2:3,20:30]

,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
2,Enr Pvt9,Enr R Govt1,Enr R Govt2,Enr R Govt3,Enr R Govt4,Enr R Govt5,Enr R Govt6,Enr R Govt7,Enr R Govt9,Enr R Pvt1

In [68]:
df2.columns =df2.iloc[2]
df2.columns
df2 = df2.iloc[3:].reset_index(drop=True)

In [69]:
df2.head(3)

2,Year,Statecd,State Name,distcd,distname,Enr Govt1,Enr Govt2,Enr Govt3,Enr Govt4,Enr Govt5,...,Rep C7,Rep C8,Muslim P,Muslim Up,Muslim G P,Muslim G Up,Obc P,Obc Up,Obc G P,Obc G Up
0,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3501,ANDAMANS ...,3232,3359,10620,0,1027,...,7,4,2539,1383,1263,690,2289,1437,1159,747
1,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3503,MIDDLE AND NORTH ANDAMANS ...,3996,3808,1162,1043,1397,...,0,0,184,103,98,60,2100,1621,1066,825
2,2012-13,35,ANDAMAN & NICOBAR ISLANDS ...,3502,NICOBARS ...,1510,886,357,0,651,...,5,2,62,34,33,14,17,5,6,0

In [9]:
df1.columns
#df2.columns
#df3.columns

Index(['Year', 'State Code', 'State Name', 'District Code', 'District Name',
       'Number of Blocks', 'Number of Clusters', 'Number of Villages',
       'Total Number of Schools', 'Total Poulation', '0-6 Population',
       'Percentage Urban Population', 'Sexratio', 'Sex Ratio 0-6',
       'Decadal Growth Rate', 'Percentage SC Population',
       'Percentage ST Population', 'Overall Literacy', 'Female Literacy'],
      dtype='object')

In [70]:
df2.columns

Index(['Year', 'Statecd', 'State Name ', 'distcd', 'distname', 'Enr Govt1',
       'Enr Govt2', 'Enr Govt3', 'Enr Govt4', 'Enr Govt5',
       ...
       'Rep C7', 'Rep C8', 'Muslim P', 'Muslim Up', 'Muslim G P',
       'Muslim G Up', 'Obc P', 'Obc Up', 'Obc G P', 'Obc G Up'],
      dtype='object', name=2, length=166)

In [80]:
df2 = df2.rename(columns={
    'State Code':'Statecd',
    'District Code':'distcd',
    'District Name':'distname'
})

In [76]:
common_cols = [
    'Year',
    #'State Code',
    #'District Code',
    'District Name'
]

for col in common_cols:
    print(col, col in df2.columns)

Year True
District Name True

In [54]:
df1_columns=df1.iloc[0]
df1.columns
#df1 = df1.iloc[1:].reset_index(drop=True)
#df1 = df1.drop(index=0)

In [86]:
#df2['distname']=df2['distname'].astype(str)
df1['distcd']=df1['distcd'].astype(int)

In [79]:
df1.columns
#= df1['District Name'].astype(str)
  #  df2['col'] = df2['col'].astype(str)

Index(['Year', 'Statecd', 'statename', 'distcd', 'distname', 'blocks',
       'clusters', 'villages', 'totschools', 'totpopulation', 'p_06_pop',
       'p_urb_pop', 'sexratio', 'sexratio_06', 'growthrate', 'p_sc_pop',
       'p_st_pop', 'overall_lit', 'female_lit'],
      dtype='object', name=0)

In [89]:
#check the data types
#df1[['Year', 'Statecd', 'distcd']].dtypes
#Check for duplicates
df1.duplicated(subset=['Year', 'Statecd', 'distcd']).sum()

np.int64(0)

In [90]:
#check the data types
#df2[['Year', 'Statecd', 'distcd']].dtypes
#Check for duplicates
df2.duplicated(subset=['Year', 'Statecd', 'distcd']).sum()

np.int64(0)

In [91]:
common=pd.merge(df1[['Year','Statecd','distcd']],
                df2[['Year','Statecd','distcd']],how='inner',
                on=['Year','Statecd','distcd'])
print(len(common))

1324

In [93]:
#df1.shape
df2.shape

(1324, 166)

In [94]:
merged_df=pd.merge(df1,df2,how='left',
                   on=['Year','Statecd','distcd'])

In [95]:
print(df1.shape)
print(df2.shape)
print(merged_df.shape)

(1324, 19)
(1324, 166)
(1324, 182)

In [96]:
merged_df.isna().sum().sort_values(ascending=False).head(20)

p_sc_pop         68
p_st_pop         68
p_urb_pop        62
p_06_pop         58
sexratio_06      58
growthrate       56
female_lit       56
overall_lit      56
sexratio         56
totpopulation    56
Nerup Cy         28
Nerp Cy          28
Gerup Cy         28
Gerp Cy          28
Enr Med2 4        8
Enr Med2 5        5
Nerp Py2          5
Enr Med3 1        5
Enr Govt6         5
Enr Med3 6        5
dtype: int64

## Exercise 2  - Data Integration (3 Marks)

As the required data is present in different datasets, we need to **integrate both to make a single dataframe/dataset**.
  * For integrating the datasets, create a unique identifier for each row in both the dataframes so that it can be used to map the data in different files.
   
    * Combine year, state code, district code columns and form a new unique identifier column, refer to this [link](https://stackoverflow.com/questions/33098383/merge-multiple-column-values-into-one-column-in-python-pandas).
    * Set the identifier column as the index for each dataframe.

    * Integrate the dataframes using the above index
     
     Hint: For merging or joining the datasets, refer to this [link](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html)

**Example:** Data of the district Anantapur in Andrapradesh, which is present in different files should form a single row after integrating the datasets

In [ ]:
# YOUR CODE HERE for integrating the datasets

## Exercise 3 - Data Cleaning (3 Marks)

1.  **Overall_lit** is our target variable. Delete rows with missing overall_lit value

   Hint: Refer to the link [dropna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html).


2.  Convert categorical values to numerical values.

  For example, If a feature contains categorical values such as dog, cat, mouse, etc then replace them with 0, 1, 2, etc or use [Sklearn LabelEncoder's](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html)

3. Replace the missing values in any other column appropriately with mean / median / mode.

  Hint: Use pandas [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) function to replace the missing values

In [ ]:
# YOUR CODE HERE for data cleaning

## Exercise 4 - (3 Marks)

1. Remove the unnecessary columns which are not contributing to the overall literacy rate

2. Verify if there are any duplicate columns and remove them.

  For example: state name and district name are the same as state code and district code.

3. Make sure that the final dataframe has no null or nan values. Delete the rows with missing values.

   Hint: Give df.isna() to verify on the nan values in the dataframe.

In [ ]:
# YOUR CODE HERE for cleaning the dataframe

## Exercise 5 - Apply Correlation Matrix (2 Marks)

Correlation is a statistical technique that can show whether and how strongly pairs of variables are related. More number of features does not imply better accuracy. More features may lead to a decline in the accuracy and create noise in the model, if they contain any irrelevant features.

*Features with high correlation value will imply the same meaning. Hence removing the highly correlated features*

**Function Description:**

`remove_Highly_Correlated()` function removes highly correlated features in the dataframe.
- Creates a correlation matrix of row and column wise features
- Extracts only uppertriangular matrix as correlation matrix, which will have the same values below and above the diagonal
- Removes columns which are having correlation value more than the threshold value.

In [ ]:
def remove_Highly_Correlated(df, bar=0.9):
  # Creates correlation matrix
  corr = df.corr()

  # Set Up Mask To Hide Upper Triangle
  mask = np.triu(np.ones_like(corr, dtype=bool))
  tri_df = corr.mask(mask)

  # Finding features with correlation value more than specified threshold value (bar=0.9)
  highly_cor_col = [col for col in tri_df.columns if any(tri_df[col] > bar )]
  print("length of highly correlated columns",len(highly_cor_col))

  # Drop the highly correlated columns
  reduced_df = df.drop(highly_cor_col, axis = 1)
  print("shape of data",df.shape,"shape of reduced data",reduced_df.shape)
  return reduced_df

In [ ]:
# YOUR CODE HERE to remove highly correlated features from the dataframe by calling above function.

## Exercise 6 - (3 Marks)

Perform Standard Scaling on the data feature/column wise.

**Hint:** In order to understand the idea behind the terms used above, you may refer to the following link:

[StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [ ]:
# YOUR CODE HERE

## Exercise 7 - (3 Marks)

Apply different classifiers on the preprocessed data and figure out which classifier gives the best result.

* Split the data into train and test

* Fit the model with train data and find the accuracy of test data

### Expected Accuracy is above 90%

In [ ]:
# YOUR CODE HERE for applying different classifiers